### ISSUE TITLE
CEF

### ISSUE THREAD

**Issue by faaactz** [Hold404/cef-template#1]
Where can i find a working CEF Version? The officlal samp-cef github version just gives me blurry results.

**Comment by Hold404** [comment]
Hi, are u talking about server side plugin or about files in game?

**Comment by faaactz** [comment]
Both. With the original the results are blurry like here: https://github.com/Pycckue-Bnepeg/samp-cef/issues/47

**Comment by Hold404** [comment]
Damn, I guess that I'cant help u. I'm not a SAMP-CEF developer, so I can't help u with your problem,
